#!/bin/sh

gnuplot -persist << EOF
set term postscript enhanced eps color 18
set autoscale
set key right top
set pointsize 1
set xlabel "epsilon"
set ylabel "<exp(-sigma)>"
set xrange [0:0.03]
set mxtics 5
set xtics 0.01
set mytics 5
set ytics 0.1
set yrange [0:0.6]
set output "sigma-compare.eps"
plot "result_sigma_50_0.1.dat" u 4:7 w lp t "50, 0.1" pt 7 lt 1 lw 2 lc rgb "red",\
"result_sigma_100_0.1.dat" u 4:7 w lp t "100, 0.1" pt 5 lt 1 lw 2 lc rgb "blue",\
"result_sigma_200_0.1.dat" u 4:7 w lp t "200, 0.1" pt 9 lt 1 lw 2 lc rgb "green",\
"result_sigma_50_0.3.dat" u 4:7 w lp t "50, 0.3" pt 65 lt 2 lw 2 lc rgb "red",\
"result_sigma_100_0.3.dat" u 4:7 w lp t "100, 0.3" pt 64 lt 2 lw 2 lc rgb "blue",\
"result_sigma_200_0.3.dat" u 4:7 w lp t "200, 0.3" pt 66 lt 2 lw 2 lc rgb "green"

EOF

#"result_sigma_50_0.1.dat" u 4:7 w pl notitle pt 7 lc rgb "red",\
