#!/bin/sh

gnuplot -persist << EOF
set term postscript enhanced eps color 26
set autoscale
set key right top
set pointsize 1
set xlabel "L eps**nu"
set ylabel "<exp(-sigma)>"
set xrange [0:3]
set mxtics 5
set xtics 1
set mytics 5
set ytics 0.1
set yrange [0:0.6]
set output "sigma-compare.eps"
plot "result_sigma_20_0.1.dat" u 4:7 w lp t "20, 0.1" pt 7 lt 1 lw 2 lc rgb "red",\
"result_sigma_40_0.1.dat" u 4:7 w lp t "40, 0.1" pt 5 lt 1 lw 2 lc rgb "blue",\
"result_sigma_50_0.1.dat" u 4:7 w lp t "50, 0.1" pt 9 lt 1 lw 2 lc rgb "green",\
"result_sigma_20_0.3.dat" u 4:7 w lp t "20, 0.3" pt 65 lt 2 lw 2 lc rgb "red",\
"result_sigma_40_0.3.dat" u 4:7 w lp t "40, 0.3" pt 64 lt 2 lw 2 lc rgb "blue",\
"result_sigma_50_0.3.dat" u 4:7 w lp t "50, 0.3" pt 66 lt 2 lw 2 lc rgb "green"

EOF

#"result_sigma_50_0.1.dat" u 4:7 w pl notitle pt 7 lc rgb "red",\
